name: CI - build & trivy scan

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-scan:
    # runs-on: ubuntu-24.04
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug env variable
        run: |
          echo "REPOSITORY_OWNER='$DOCKER_REPOSITORY_OWNER_USERNAME'"
          env | grep OWNER

      - name: Build Docker image
        run: |
          docker build \
            -t docker.io/${{ vars.DOCKER_REPOSITORY_OWNER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Run Trivy (vulnerability scan)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: docker.io/${{ vars.DOCKER_REPOSITORY_OWNER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          format: json
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: trivy-report.json

      - name: Send Trivy Report to Slack
        run: |
          STATUS=$(jq '.Results[].Vulnerabilities | length' trivy-report.json | awk '{s+=$1} END {print s}')

          if [ "$STATUS" -gt 0 ]; then
            MSG="*Trivy Scan Completed with* $STATUS vulnerabilities"
          else
            MSG="*Trivy Scan Passed â€” No High/Critical vulnerabilities*"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"$MSG\",
              \"attachments\": [
                {
                  \"fallback\": \"Trivy Report\",
                  \"text\": \"\`\`\`$(jq '.' trivy-report.json)\`\`\`\"
                }
              ]
            }" \
            ${{ secrets.MATTERMOST_WEBHOOK_URL }}

      - name: Push Docker image
        if: success()
        run: |
          docker push docker.io/${{ vars.DOCKER_REPOSITORY_OWNER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}
