name: CI - build & trivy scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-scan:
    # runs-on: ubuntu-24.04
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug env variable
        run: |
          echo "REPOSITORY_OWNER='$DOCKER_REPOSITORY_OWNER_USERNAME'"
          env | grep OWNER

      - name: Build Docker image
        run: |
          docker build \
            -t docker.io/${{ vars.DOCKER_REPOSITORY_OWNER_USERNAME }}/my-app:${{ github.sha }} \
            .

      # - name: Run Trivy (vulnerability scan) and produce SARIF
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: docker.io/${{ vars.DOCKER_REPOSITORY_OWNER_USERNAME }}/my-app:${{ github.sha }}
      #     format: sarif
      #     output: trivy-report.sarif
      #     exit-code: '0'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'

      # - name: Upload SARIF for GitHub code scanning
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: trivy-report.sarif

      - name: Run Trivy (vulnerability scan)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: docker.io/${{ vars.DOCKER_REPOSITORY_OWNER_USERNAME }}/my-app:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
